name: Check Project with Secrets

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

  pull_request_target:
    types:
      - labeled
    paths-ignore:
      - '**.md'

jobs:
  rspec:
    if: ${{ github.event_name != 'pull_request_target' || contains(github.event.pull_request.labels.*.name, 'run ci') }}
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: run ci

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Run RSpec
        run: bundle exec rspec

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
