name: Release Gem

on:
  push:
    branches:
      - main
    paths:
      - 'lib/net/http/structured_field_values/version.rb'

jobs:
  check:
    outputs:
      source_version: ${{ steps.versions.outputs.source_version }}
      gem_version: ${{ steps.versions.outputs.gem_version }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version

      - name: Set versions
        id: versions
        run: |
          echo "source_version=$(.github/workflows/print-version.rb source)" >> "$GITHUB_OUTPUT"
          echo "gem_version=$(.github/workflows/print-version.rb gem)" >> "$GITHUB_OUTPUT"

  release:
    needs: check
    if: ${{ needs.check.outputs.source_version != needs.check.outputs.gem_version }}

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Release gem
        run: |
          sudo apt-get install -y oathtool
          GEM_HOST_OTP_CODE=$(oathtool --totp -d 6 -b ${{ secrets.RUBYGEMS_OTP_SECRET }})\
            bundle exec rake release
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
